spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://mysql-aws.c4v3j9tgecmv.us-east-1.rds.amazonaws.com:3306/itemsharingdatabase"
    username: "root"
    password: "{cipher}bd6760aaeb2a3184c816eb8818831f6ae7c95e03d8f2558e14632ba8d39391ed"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    
security:
  oauth2:
    resource:
      user-info-uri: http://54.235.233.109:8901/user
    
server:
  port: 8901
  
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://54.235.233.109:8761/eureka
      
signing:
  key: 345345fsdgsf5345

management:
  security:
    enabled: false