spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
    username: "root"
    password: "{cipher}bd6760aaeb2a3184c816eb8818831f6ae7c95e03d8f2558e14632ba8d39391ed"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    
    
server:
  port: 8081

eureka:
  instance:
    perferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
 oauth2:
  resource:
    userInfoUri: http://localhost:8901/user
    
signing:
  key: 345345fsdgsf5345
  
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG